package com.forever.fengyuchenglun.commit.ui;

import com.forever.fengyuchenglun.commit.CommitSetting;
import com.forever.fengyuchenglun.commit.model.ChangeScope;
import com.forever.fengyuchenglun.commit.model.ChangeType;
import com.forever.fengyuchenglun.commit.ui.CommitTable;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.ToolbarDecorator;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.stream.Collectors;

/**
 * @author duanledexianxianxian
 * @data 2019/2/15
 */
public class ConfigCommitForm {
    private JPanel mainPanel;
    private CommitSetting commitSetting;
    private CommitTable changeTypeTable;
    private CommitTable changeScopeTable;
    private String[] changeTypeColumnNames = {"Type", "Description"};
    private String[] changeScopeColumnNames = {"Scope", "Description"};

    public ConfigCommitForm(CommitSetting commitSetting) {
        this.commitSetting = commitSetting;
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));

        changeTypeTable = new CommitTable(commitSetting.getChangeTypeList().stream().collect(Collectors.toMap(ChangeType::getType, x -> x.getDescription())), Arrays.asList(changeTypeColumnNames));
        JPanel changeTypeLocalPanel = ToolbarDecorator.createDecorator(changeTypeTable).createPanel();
        JPanel changeTypePanel = new JPanel(new BorderLayout());
        changeTypePanel.setBorder(IdeBorderFactory.createTitledBorder("Change of Type", false, new Insets(0, 0, 10, 0)));
        changeTypePanel.add(changeTypeLocalPanel, BorderLayout.CENTER);

        changeScopeTable = new CommitTable(commitSetting.getChangeScopeList().stream().collect(Collectors.toMap(ChangeScope::getScope, x -> x.getDescription())), Arrays.asList(changeScopeColumnNames));
        JPanel changeScopeLocalPanel = ToolbarDecorator.createDecorator(changeScopeTable).createPanel();
        JPanel changeScopePanel = new JPanel(new BorderLayout());
        changeScopePanel.setBorder(IdeBorderFactory.createTitledBorder("Change of Scope", false, new Insets(0, 0, 10, 0)));
        changeScopePanel.add(changeScopeLocalPanel, BorderLayout.CENTER);

        mainPanel.add(changeTypePanel, getConstraints(0, 0));
        mainPanel.add(changeScopePanel, getConstraints(1, 0));
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }


    private GridConstraints getConstraints(int row, int column) {
        return new GridConstraints(row, column, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
